%YAML:1.0
# Default params
# camera_calibration_file: "kinect_default.yaml"
# index_file: "index.txt"
# aruco_dic: "ARUCO"
# aruco_marker_size: 0.1778
# aruco_distance: 4
camera_calibration_file: "kinect_default.yaml"
index_file: "/Users/bruno/Box_Sync/RGBD_TUM/rgbd_dataset_freiburg1_xyz/index"
aruco_dic: "ARUCO"
aruco_max_distance: 4
aruco_marker_size: 0.1778








